[package]
name = "pisugar-server"
version = "0.1.0"
authors = ["PiSugar"]
edition = "2018"

[dependencies]
log = "0.4.8"
env_logger = "0.7"
bytes = "0.5.4"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
tokio = { version = "0.2", features = ["full"] }
tokio-util = "0.2"
tokio-tungstenite = "0.10.1"
futures = "0.3"
futures-util = "0.3"
futures-channel = "0.3"
hyper = "0.13"
pisugar-core = { path = "../pisugar-core" }