name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - continue-on-error: false
      - uses: actions/checkout@v2

  nodejs-build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    - continue-on-error: false
    # Nodejs
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    # Nodejs cache
    - name: Nodejs cache
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    # Nodejs dependencies
    - run: npm install
      working-directory: electron
    # Nodejs build web
    - run: npm run build:web
      working-directory: electron

  rust-build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    - continue-on-error: false
    # Rust cache
    - name: Rust cargo cache
      uses: actions/cache@v1
      env:
        cache-name: cache-rust-cargo
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    # Rust target cache
    - name: Rust target cache
      uses: actions/cache@v1
      env:
        cache-name: cache-rust-target
      with:
        path: target
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    # Rust target arm-unknown-linux-gnueabihf
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: arm-unknown-linux-gnueabihf
        override: true
    # Rust cross build
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --target arm-unknown-linux-gnueabihf --release
    - run: |
        mkdir -p target/arm-unknown-linux-gnueabihf/release
        cp -rf target/release/* target/arm-unknown-linux-gnueabihf/release/

  deb-packaging:
    runs-on: ubuntu-latest
    needs: [nodejs-build, rust-build]
    steps:
    - continue-on-error: false
    # Rust cargo-deb
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-deb
        version: latest
    # Rust cargo deb
    - uses: actions-rs/cargo@v1
      with:
        command: deb
        args: --target arm-unknown-linux-gnueabihf --manifest-path=pisugar-server/Cargo.toml --no-build --no-strip

  upload-artifact:
    runs-on: ubuntu-latest
    needs: deb-packaging
    steps:
    - continue-on-error: false
    # Upload artifact
    - uses: actions/upload-artifact@v1
      with:
        name: pisugar-server-deb
        path: target/arm-unknown-linux-gnueabihf/debian