name: Release QiNiu

on:
  release:
    types: [published]

jobs:
  upload-qiniu:
    name: "Upload to QiNiu"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Upload to QiNiu"
        env:
          QINUE_BUCKET: ${{ secrets.QINUE_BUCKET }}
          QINUE_AK: ${{ secrets.QINUE_AK }}
          QINUE_SK: ${{ secrets.QINUE_SK }}
        run: |
          sudo apt-get install -y openjdk-11-jre
          if [ $(uname -m) == 'x86_64' ]; then
            wget -O qsuits http://devtools.qiniu.com/qsuits_linux_amd64
          else
            wget -O qsuits http://devtools.qiniu.com/qsuits_linux_386
          fi
          chmod +x qsuits

          curl https://api.github.com/repos/PiSugar/pisugar-power-manager-rs/releases/latest > latest

          sudo apt-get install -y jq
          for url in $(jq '.assets[].browser_download_url' latest); do
            url=$(echo $url | awk -F '"' '{print $2}')
            filename=${url##*/}
            wget -O ${filename} ${url}
            ./qsuits -process=qupload -s -path=${filename} -ak=${QINUE_AK} -sk=${QINUE_SK} -bucket=${QINUE_BUCKET} -key=${filename}
          done
