name: Release QiNiu

on:
  release:
    types: [published]

jobs:
  upload-qiniu:
    name: "Upload to QiNiu"
    runs-on: "ubuntu-latest"
    steps:
    - name: "Upload to QiNiu"
      env:
        QINUE_BUCKET: ${{ secrets.QINUE_BUCKET }}
        QINUE_AK: ${{ secrets.QINUE_AK }}
        QINUE_SK: ${{ secrets.QINUE_SK }}
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip

        if [ $(uname -m) == 'x86_64' ]; then
          wget http://devtools.qiniu.com/qshell-linux-x64-v2.4.1.zip
          unzip qshell-linux-x64-v2.4.1.zip
          mv qshell-linux-x64-v2.4.1 qshell
        else
          wget http://devtools.qiniu.com/qshell-linux-x86-v2.4.1.zip
          unzip qshell-linux-x86-v2.4.1.zip
          mv qshell-linux-x86-v2.4.1 qshell
        fi
        chmod +x qshell
        ./qshell account -w ${QINIU_AK} ${QINIU_SK} deploy-account

        curl https://api.github.com/repos/PiSugar/pisugar-power-manager-rs/releases/latest > latest

        sudo apt-get install -y jq
        for url in $(jq '.assets[].browser_download_url' latest); do
          url=$(echo $url | awk -F '"' '{print $2}')
          filename=${url##*/}
          ./qshell sync ${url} ${QINIU_BUCKET} -k ${filename}
        done